version: '2'
services:
  db-primary:
    image: postgres
  db-secondary:
    image: postgres
  db-candidate:
    image: postgres
  diffy:
    image: camiloribeiro/twitter-diffy
    ports:
      - "8888:8888"
      - "31900:31900"
      - "8881:8881"
    depends_on:
      - primary
      - secondary
      - candidate
    command: java -jar ./target/scala-2.11/diffy-server.jar -candidate='candidate:3000' -master.primary='primary:3000' -master.secondary='secondary:3000' -service.protocol='http' -serviceName='Happy Service' -proxy.port=:31900 -admin.port=:8881 -http.port=:8888 -rootUrl='localhost:8888'

  candidate:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../candidate:/myapp
    ports:
      - "9881:3000"
    depends_on:
      - db-candidate
  primary:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../primary:/myapp
    ports:
      - "9882:3000"
    depends_on:
      - db-primary

  secondary:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../secondary:/myapp
    ports:
      - "9883:3000"
    depends_on:
      - db-secondary
