version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  hub:
    image: elgalu/selenium
    ports:
      - ${SELENIUM_HUB_PORT}:${SELENIUM_HUB_PORT}
      # We need a fixed port range to expose VNC
      # due to a bug in Docker for Mac beta (1.12)
      # https://forums.docker.com/t/docker-for-mac-beta-not-forwarding-ports/8658/6
      - ${VNC_FROM_PORT}-${VNC_TO_PORT}:${VNC_FROM_PORT}-${VNC_TO_PORT}
      # e.g. (hard-coded)
      # - 40650-40700:40650-40700
    environment:
      - SELENIUM_HUB_PORT
      - PICK_ALL_RANDMON_PORTS=true
      - GRID=true
      - CHROME=false
      - FIREFOX=false
    container_name: hub
    hostname: hub
  chrome:
    image: elgalu/selenium
    network_mode: "service:hub"
    shm_size: 1g
    mem_limit: 2g
    memswap_limit: 4g
    # 90000 means 90%
    # cpu_quota: 90000
    environment:
      - SELENIUM_HUB_PORT
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - VIDEO
      - GRID=false
      - CHROME=true
      - FIREFOX=false
      - VNC_PASSWORD=hola
  firefox:
    image: elgalu/selenium
    network_mode: "service:hub"
    mem_limit: 2g
    memswap_limit: 4g
    # 90000 means 90%
    # cpu_quota: 90000
    environment:
      - SELENIUM_HUB_PORT
      - VNC_FROM_PORT
      - VNC_TO_PORT
      - SCREEN_WIDTH=1300
      - SCREEN_HEIGHT=999
      - PICK_ALL_RANDMON_PORTS=true
      - VIDEO
      - GRID=false
      - CHROME=false
      - FIREFOX=true
      - VNC_PASSWORD=hola
